from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field

from aether.planning.types import CognitivePlan


@dataclass(frozen=True)
class ValidationResult:
    """
    Immutable representation of a cognitive plan's validity.
    Generated by a PlanValidator before execution.
    """
    is_valid: bool
    errors: tuple[str, ...] = ()


class PlanValidator(ABC):
    """
    Abstract base class for cognitive plan validators.
    A validator checks a CognitivePlan for logical consistency,
    existence of referenced tools/skills, and adherence to constraints
    *before* the plan is compiled and executed.
    """

    @abstractmethod
    def validate(self, plan: CognitivePlan) -> ValidationResult:
        """
        Validate the cognitive plan.

        Args:
            plan: The CognitivePlan to validate.

        Returns:
            ValidationResult indicating whether the plan is valid and any errors.
        """
        pass
