from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
import re
from typing import Any

from aether.core.secrets import is_secret_key
from aether.planning.contracts import (
    ClarificationRequirement,
    ContextPack,
    MissionProposal,
    OutcomeKind,
    ProposalStatus,
    ProposalValidationResult,
    ProposalValidationStatus,
    ResolutionState,
    VerificationMethod,
)
from aether.planning.types import CognitivePlan


@dataclass(frozen=True)
class ValidationResult:
    """
    Immutable representation of a cognitive plan's validity.
    Generated by a PlanValidator before execution.
    """
    is_valid: bool
    errors: tuple[str, ...] = ()


class PlanValidator(ABC):
    """
    Abstract base class for cognitive plan validators.
    A validator checks a CognitivePlan for logical consistency,
    existence of referenced tools/skills, and adherence to constraints
    *before* the plan is compiled and executed.
    """

    @abstractmethod
    def validate(self, plan: CognitivePlan) -> ValidationResult:
        """
        Validate the cognitive plan.

        Args:
            plan: The CognitivePlan to validate.

        Returns:
            ValidationResult indicating whether the plan is valid and any errors.
        """
        pass


class ProposalValidator:
    """
    Deterministic validator for MissionProposals (Phase A Macro-pass 1).
    Distinguishes VALID, REQUIRES_CLARIFICATION, INVALID, and FAILED states.
    Enforces architectural invariants:
      - Workspace scoping integrity.
      - Lifecycle state consistency.
      - Zero secrets / credentials in proposals.
      - Outcome constraint validity (no completed outcomes without evidence).
      - No contradictory constraints.
      - No claimed unavailable evidence.
      - No execution side-effects during generation.
      - Required approval boundaries preserved.
    """

    SECRET_PATTERNS = [
        re.compile(r"ghp_[a-zA-Z0-9]{36}"),             # GitHub PAT
        re.compile(r"xoxb-[0-9]{11,13}-[a-zA-Z0-9]+"),   # Slack bot token
        re.compile(r"-----BEGIN (?:RSA |EC )?PRIVATE KEY-----"),
        re.compile(r"\b(?:bearer\s+[a-zA-Z0-9_\-\.]{20,})\b", re.IGNORECASE),
        re.compile(r"\b(?:api[_-]?key|secret|password)\s*[:=]\s*['\"][^'\"]{6,}['\"]", re.IGNORECASE),
        re.compile(r"\b(?:sentinel_secret_[a-zA-Z0-9_]+)\b", re.IGNORECASE),
    ]

    SENSITIVE_ACTIONS = {
        "email.send": "External email communication",
        "slack.send_message": "External Slack messaging",
        "telegram.send_message": "External Telegram messaging",
        "github.create_pull_request": "Remote PR creation",
        "github.create_branch": "Remote branch mutation",
        "files.delete": "Destructive filesystem operation",
        "agents.delegate_external": "External worker delegation",
    }

    COMPATIBLE_VERIFICATION_METHODS: dict[str, set[str]] = {
        OutcomeKind.PULL_REQUEST_CREATED.value: {
            VerificationMethod.PROVIDER_EVIDENCE.value,
            VerificationMethod.MANUAL_REVIEW.value,
            VerificationMethod.VERIFICATION_UNAVAILABLE.value,
        },
        OutcomeKind.FILES_MODIFIED.value: {
            VerificationMethod.FILESYSTEM_DIFF.value,
            VerificationMethod.GIT_STATUS.value,
            VerificationMethod.MANUAL_REVIEW.value,
        },
        OutcomeKind.TESTS_PASSED.value: {
            VerificationMethod.TEST_RUNNER.value,
            VerificationMethod.MANUAL_REVIEW.value,
        },
        OutcomeKind.REPORT_GENERATED.value: {
            VerificationMethod.FILE_EXISTENCE.value,
            VerificationMethod.CHECKSUM.value,
            VerificationMethod.MANUAL_REVIEW.value,
        },
        OutcomeKind.EMAIL_SENT.value: {
            VerificationMethod.DELIVERY_RECEIPT.value,
            VerificationMethod.PROVIDER_EVIDENCE.value,
            VerificationMethod.MANUAL_REVIEW.value,
            VerificationMethod.VERIFICATION_UNAVAILABLE.value,
        },
        OutcomeKind.DELIVERABLE_CREATED.value: {
            VerificationMethod.FILE_EXISTENCE.value,
            VerificationMethod.CHECKSUM.value,
            VerificationMethod.MANUAL_REVIEW.value,
        },
    }

    def validate(
        self,
        proposal: MissionProposal,
        context: ContextPack | None = None,
    ) -> ProposalValidationResult:
        """
        Validates a MissionProposal against strict safety and truthfulness invariants.
        """
        errors: list[str] = []
        warnings: list[str] = []
        clarifications: list[ClarificationRequirement] = list(proposal.clarification_requirements)

        # 1. Workspace scope check
        if not proposal.workspace_id or not proposal.workspace_id.strip():
            errors.append("Proposal lacks mandatory workspace_id scope.")

        if context is not None:
            if proposal.workspace_id.strip() != context.workspace_scope.strip():
                errors.append(
                    f"Workspace scope mismatch: proposal has '{proposal.workspace_id}' "
                    f"but context pack has '{context.workspace_scope}'."
                )

        # 2. Lifecycle state consistency
        if proposal.status == ProposalStatus.READY_FOR_ACCEPTANCE:
            blocking = [c for c in clarifications if c.blocking]
            if blocking:
                errors.append(
                    f"Proposal is marked READY_FOR_ACCEPTANCE but has {len(blocking)} blocking clarification requirements."
                )
            if context is not None:
                unres = [
                    e for e in context.resolved_entities
                    if e.resolution_state in (ResolutionState.UNRESOLVED, ResolutionState.NOT_FOUND, ResolutionState.AMBIGUOUS)
                ]
                if unres:
                    errors.append(
                        f"Proposal marked READY_FOR_ACCEPTANCE cannot have ambiguous or unresolved entities: "
                        f"{', '.join(f'{e.entity_type}:{e.display_name}' for e in unres)}."
                    )
                if context.ambiguity:
                    errors.append(
                        f"Proposal marked READY_FOR_ACCEPTANCE cannot have unresolved context ambiguities: "
                        f"{'; '.join(context.ambiguity)}."
                    )
                if context.unresolved_references:
                    errors.append(
                        f"Proposal marked READY_FOR_ACCEPTANCE cannot have unresolved references: "
                        f"{', '.join(context.unresolved_references)}."
                    )
            if proposal.confidence < 0.5:
                errors.append(
                    f"Proposal marked READY_FOR_ACCEPTANCE has insufficient confidence ({proposal.confidence})."
                )

        # 3. Secret and Sensitive Payload Detection
        self._scan_for_secrets(proposal, context, errors)

        # 4. Outcome Constraints Verification
        self._validate_outcome_constraints(proposal, errors, warnings)

        # 5. Contradictory Constraints Check
        self._validate_contradictory_constraints(proposal, errors)

        # 6. Evidence Availability Check
        if context is not None:
            self._validate_evidence_availability(proposal, context, errors)

        # 7. Premature Execution Check
        self._validate_no_premature_execution(proposal, errors)

        # 8. Approval Boundaries Check
        self._validate_approval_boundaries(proposal, errors)

        # Determine final status
        if proposal.status == ProposalStatus.FAILED or (context and context.retrieval_failures and not context.resolved_entities):
            final_status = ProposalValidationStatus.FAILED
            is_valid = False
        elif errors:
            final_status = ProposalValidationStatus.INVALID
            is_valid = False
        elif any(c.blocking for c in clarifications) or proposal.status == ProposalStatus.NEEDS_CLARIFICATION:
            final_status = ProposalValidationStatus.REQUIRES_CLARIFICATION
            is_valid = False
        else:
            final_status = ProposalValidationStatus.VALID
            is_valid = True

        return ProposalValidationResult(
            status=final_status,
            is_valid=is_valid,
            errors=errors,
            warnings=warnings,
            clarification_requirements=clarifications,
            metadata={
                "proposal_id": proposal.id,
                "version": proposal.version,
                "confidence": proposal.confidence,
                "inspected_steps_count": len(proposal.proposed_steps),
            },
        )

    SENSITIVE_KEY_SUBSTRINGS = (
        "token",
        "secret",
        "password",
        "api_key",
        "auth",
        "credential",
        "private_key",
        "access_key",
        "refresh_token",
        "client_secret",
        "authorization",
    )

    def _scan_for_secrets(
        self,
        proposal: MissionProposal,
        context: ContextPack | None,
        errors: list[str],
    ) -> None:
        """Verifies that no secrets or credentials leak into proposal or context structures structurally."""
        def check_structure(obj: Any, path: str = "root") -> None:
            if isinstance(obj, dict):
                for k, v in obj.items():
                    kl = str(k).lower()
                    field_path = f"{path}.{k}"
                    if any(s in kl for s in self.SENSITIVE_KEY_SUBSTRINGS):
                        errors.append(f"Security invariant violated: Sensitive key '{k}' detected at '{field_path}'.")
                    check_structure(v, field_path)
            elif isinstance(obj, (list, tuple, set)):
                for idx, item in enumerate(obj):
                    check_structure(item, f"{path}[{idx}]")
            elif isinstance(obj, str):
                for pattern in self.SECRET_PATTERNS:
                    if pattern.search(obj):
                        errors.append(f"Security invariant violated: Secret credential pattern detected in value at '{path}'.")
                        break

        # Check proposal serialized dictionary
        check_structure(proposal.to_dict(), path="proposal")

        # Check context if provided
        if context is not None:
            check_structure(context.to_dict(), path="context")

    def _validate_outcome_constraints(
        self,
        proposal: MissionProposal,
        errors: list[str],
        warnings: list[str],
    ) -> None:
        """Validates that outcome constraints are well-formed and verifiable."""
        valid_kinds = {k.value for k in OutcomeKind}
        valid_methods = {m.value for m in VerificationMethod}

        for oc in proposal.outcome_constraints:
            if not oc.description:
                errors.append(f"Outcome constraint '{oc.id}' lacks a description.")
            if oc.verification_method not in valid_methods:
                errors.append(
                    f"Outcome constraint '{oc.id}' specifies unsupported verification method '{oc.verification_method}'."
                )

            # Check compatibility between outcome kind and verification method
            if oc.kind in self.COMPATIBLE_VERIFICATION_METHODS:
                compatible = self.COMPATIBLE_VERIFICATION_METHODS[oc.kind]
                if oc.verification_method not in compatible:
                    errors.append(
                        f"Truthfulness invariant violated: outcome '{oc.kind}' has incompatible verification method "
                        f"'{oc.verification_method}'; compatible methods are: {', '.join(sorted(compatible))}."
                    )

            # Invariant: an outcome cannot be verified before execution has occurred
            if oc.status in ("verified", "completed", "succeeded") and not oc.evidence_refs:
                errors.append(
                    f"Truthfulness invariant violated: outcome constraint '{oc.id}' claims status '{oc.status}' "
                    f"prior to execution without verified evidence."
                )

    def _validate_contradictory_constraints(self, proposal: MissionProposal, errors: list[str]) -> None:
        """Detects mutually conflicting constraints in proposal."""
        c_lower = [c.lower() for c in proposal.constraints]
        all_actions = []
        for s in proposal.proposed_steps:
            all_actions.extend([a.lower() for a in s.required_tools_or_actions])

        # Example: read-only constraint vs mutating actions
        is_readonly = any("read-only" in c or "no mutations" in c or "read only" in c for c in c_lower)
        has_mutation = any(
            any(m in a for m in ["create", "update", "delete", "write", "send"])
            for a in all_actions
        )
        if is_readonly and has_mutation:
            errors.append("Contradictory constraints: proposal specifies read-only mode but includes mutating actions.")

    def _validate_evidence_availability(
        self,
        proposal: MissionProposal,
        context: ContextPack,
        errors: list[str],
    ) -> None:
        """Verifies that evidence claimed by proposal exists in context pack."""
        available_ev_ids = {ev.id for ev in context.evidence_references}
        for oc in proposal.outcome_constraints:
            for ev_ref in oc.evidence_refs:
                if ev_ref not in available_ev_ids:
                    errors.append(
                        f"Outcome constraint '{oc.id}' claims evidence '{ev_ref}' not found in ContextPack."
                    )

    def _validate_no_premature_execution(self, proposal: MissionProposal, errors: list[str]) -> None:
        """Ensures proposal generation did not trigger mission creation or runtime execution."""
        if proposal.provenance and proposal.provenance.metadata:
            meta = proposal.provenance.metadata
            if meta.get("mission_id") or meta.get("execution_id"):
                errors.append("Proposal generation violated invariant: mission or execution record was created prematurely.")

    def _validate_approval_boundaries(self, proposal: MissionProposal, errors: list[str]) -> None:
        """Ensures all sensitive operations have declared approval boundaries."""
        declared_actions = {a.action_or_boundary for a in proposal.required_approvals}
        for step in proposal.proposed_steps:
            for action in step.required_tools_or_actions:
                if action in self.SENSITIVE_ACTIONS and action not in declared_actions:
                    errors.append(
                        f"Approval boundary missing: step '{step.title}' includes sensitive action '{action}' "
                        f"({self.SENSITIVE_ACTIONS[action]}) without declared RequiredApprovalSpec."
                    )
