"""
Test suite for Automatic DMG Build Pipeline (DSK-05).

Covers:
- DSK-05-A: ui/package.json and tauri.conf.json script contracts (recursion prevention)
- DSK-05-B: Static assets synchronization from ui/dist to src/aether/server/static
- DSK-05-C: Fail-safe behavior on missing frontend distribution artifacts
- DSK-05-D: Presence and integrity of build/Aether.dmg generated via the automated pipeline
- DSK-05-E: Mountability and layout validation of the pipeline-generated DMG
"""
import json
import os
import plistlib
import shutil
import subprocess
from pathlib import Path
import pytest


def _get_repo_root() -> Path:
    current = Path(__file__).resolve().parent
    while current != current.parent:
        if (current / "pyproject.toml").exists() and (current / "src").exists():
            return current
        current = current.parent
    return Path.cwd()


def test_dsk_05_scripts_contract():
    """Verify package.json and tauri.conf.json script configurations prevent recursion."""
    repo_root = _get_repo_root()
    ui_package_json = repo_root / "ui" / "package.json"
    tauri_conf = repo_root / "src-tauri" / "tauri.conf.json"

    assert ui_package_json.exists()
    assert tauri_conf.exists()

    with open(ui_package_json, "r", encoding="utf-8") as f:
        pkg_data = json.load(f)

    scripts = pkg_data.get("scripts", {})
    assert "build:ui" in scripts, "build:ui script missing in ui/package.json"
    assert "tsc -b && vite build" in scripts["build:ui"]
    assert "build" in scripts, "build script missing in ui/package.json"
    assert "package_after_build.py" in scripts["build"], "package_after_build.py not chained in npm run build"

    with open(tauri_conf, "r", encoding="utf-8") as f:
        tauri_data = json.load(f)

    before_build = tauri_data.get("build", {}).get("beforeBuildCommand", "")
    assert "build:ui" in before_build, (
        f"tauri.conf.json beforeBuildCommand should call build:ui to prevent recursion, got: '{before_build}'"
    )


def test_dsk_05_static_asset_sync(tmp_path):
    """Verify frontend static assets sync cleanly to Python server static directory."""
    repo_root = _get_repo_root()
    ui_dist = repo_root / "ui" / "dist"
    server_static = repo_root / "src" / "aether" / "server" / "static"

    assert ui_dist.exists(), "ui/dist must exist"
    assert (ui_dist / "index.html").exists(), "ui/dist/index.html must exist"
    assert server_static.exists(), "src/aether/server/static must exist"
    assert (server_static / "index.html").exists(), "src/aether/server/static/index.html must exist"

    # Compare content of index.html
    with open(ui_dist / "index.html", "rb") as f1, open(server_static / "index.html", "rb") as f2:
        assert f1.read() == f2.read(), "server/static/index.html does not match ui/dist/index.html"


def test_dsk_05_dmg_integrity():
    """Verify build/Aether.dmg generated by the pipeline is valid and mountable."""
    repo_root = _get_repo_root()
    dmg_path = repo_root / "build" / "Aether.dmg"

    assert dmg_path.exists(), f"build/Aether.dmg not found at {dmg_path}"
    dmg_size_mb = dmg_path.stat().st_size / (1024 * 1024)
    assert dmg_size_mb > 10.0, f"DMG is smaller than 10MB: {dmg_size_mb:.2f} MB"

    # Mount DMG and verify volume contents
    mount_out = subprocess.check_output(["hdiutil", "attach", str(dmg_path), "-plist"]).decode()
    plist_data = plistlib.loads(mount_out.encode("utf-8"))

    mount_point = None
    for entity in plist_data.get("system-entities", []):
        if "mount-point" in entity:
            mount_point = Path(entity["mount-point"])
            break

    assert mount_point is not None, "Failed to mount DMG volume"

    try:
        app_in_dmg = mount_point / "Aether.app"
        apps_link = mount_point / "Applications"

        assert app_in_dmg.exists(), "Aether.app missing in DMG"
        assert apps_link.exists() or apps_link.is_symlink(), "Applications symlink missing in DMG"

        # Check binary in DMG
        main_bin = app_in_dmg / "Contents" / "MacOS" / "aether-desktop"
        assert main_bin.exists(), "aether-desktop executable missing in DMG"
        assert os.access(main_bin, os.X_OK), "aether-desktop lacks +x in DMG"
    finally:
        subprocess.run(["hdiutil", "detach", str(mount_point)], check=True)
