"""
Aether CLI — command-line interface for the Aether runtime.

Commands:
  aether init [name]              Scaffold a new team project
  aether run "task"               Run a task through the team (team.yaml)
  aether knowledge add <path>     Ingest documents into knowledge store
  aether knowledge list           List indexed knowledge sources
  aether knowledge clear          Remove all knowledge chunks
  aether knowledge search <q>     Search the knowledge base
  aether agent memory <name>      Show an agent's semantic memory facts
  aether team status              Show team agents and configuration
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _find_team_yaml(start: Path | None = None) -> Path | None:
    """Search for team.yaml in the current directory (no recursive search)."""
    search_dir = start or Path.cwd()
    candidate = search_dir / "team.yaml"
    return candidate if candidate.exists() else None


def _default_knowledge_db(team_dir: Path) -> str:
    """Return the default knowledge DB path for a given team directory."""
    return str(team_dir / ".aether" / "knowledge.db")


def _load_team_config(team_yaml: Path):
    from aether.team.loader import TeamLoader
    return TeamLoader.from_yaml(team_yaml)


# ---------------------------------------------------------------------------
# Init
# ---------------------------------------------------------------------------

def _cmd_init(args) -> None:
    name = args.name or Path.cwd().name
    target = Path(name) if args.name else Path.cwd()

    if args.name and target.exists() and any(target.iterdir()):
        print(f"Error: Directory '{name}' is not empty.", file=sys.stderr)
        sys.exit(1)

    target.mkdir(parents=True, exist_ok=True)
    (target / "knowledge").mkdir(exist_ok=True)
    (target / ".aether").mkdir(exist_ok=True)

    provider = args.provider or "openai"
    model = args.model or ("gpt-4o" if provider == "openai" else "llama3")

    team_yaml = f"""# Aether Team Configuration
# Generated by: aether init

team:
  name: {name}
  knowledge: ./knowledge/    # Drop your documents here
  provider: {provider}
  model: {model}

agents:
  - name: coordinator
    role: >
      You are the coordinator of this team. You receive tasks from the user,
      break them down, and delegate to the appropriate agents.
    relationships:
      - delegates_to: analyst
      - delegates_to: writer

  - name: analyst
    role: >
      You are a research analyst. You gather information, analyze data,
      and produce structured summaries for the coordinator and writer.

  - name: writer
    role: >
      You are a professional writer. You receive research and briefs from
      the coordinator and analyst, and produce polished, professional documents.
"""

    readme = f"""# {name}

An Aether team project.

## Quick Start

1. **Add your knowledge documents:**
   ```
   aether knowledge add ./knowledge/
   ```
   Or drop files directly into the `knowledge/` folder and run:
   ```
   aether knowledge add ./knowledge/
   ```

2. **Set your API key:**
   ```
   export OPENAI_API_KEY="your-key"
   # or for Ollama (local, no key needed):
   # edit team.yaml and set provider: ollama
   ```

3. **Run a task:**
   ```
   aether run "Draft a proposal for our new product feature"
   ```

4. **Check team status:**
   ```
   aether team status
   ```

## Team Structure

- **coordinator** — receives tasks, delegates to the team
- **analyst** — researches and analyzes
- **writer** — produces professional documents

Edit `team.yaml` to customize your team.
"""

    (target / "team.yaml").write_text(team_yaml, encoding="utf-8")
    (target / "README.md").write_text(readme, encoding="utf-8")
    (target / "knowledge" / ".gitkeep").write_text("")

    print(f"✓ Aether team project initialized: {target.resolve()}")
    print()
    print("  Next steps:")
    print(f"    cd {target}")
    print(f"    # Drop documents into knowledge/")
    print(f"    aether knowledge add ./knowledge/")
    print(f"    aether run \"Your first task\"")


# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------

def _cmd_run(args) -> None:
    team_yaml = _find_team_yaml()
    if team_yaml is None:
        print(
            "Error: No team.yaml found in the current directory.\n"
            "Run 'aether init' to create a new team project.",
            file=sys.stderr,
        )
        sys.exit(1)

    task = " ".join(args.task) if isinstance(args.task, list) else args.task
    if not task:
        print("Error: Please provide a task description.", file=sys.stderr)
        sys.exit(1)

    try:
        config = _load_team_config(team_yaml)
    except Exception as exc:
        print(f"Error loading team.yaml: {exc}", file=sys.stderr)
        sys.exit(1)

    # Build provider
    provider = _build_provider(config, args)
    if provider is None:
        sys.exit(1)

    # Load knowledge store
    kb_path = _default_knowledge_db(team_yaml.parent)
    knowledge = None
    if Path(kb_path).exists():
        from aether.knowledge.store import KnowledgeStore
        knowledge = KnowledgeStore(kb_path)

    from aether.team.team import Team

    try:
        team = Team(config, provider=provider, knowledge_store=knowledge)
    except Exception as exc:
        print(f"Error building team: {exc}", file=sys.stderr)
        sys.exit(1)

    print(f"[Aether] Team '{config.name}' — {len(team.agents())} agenti")
    print(f"[Aether] Task: {task}")
    print()

    result = team.run(task)

    print()
    if result.success:
        print(f"Risultato:\n{result.output}")
    else:
        print(f"Errore: {result.error}", file=sys.stderr)
        sys.exit(1)


def _build_provider(config, args):
    """Instantiate the provider from config + CLI overrides."""
    provider_name = getattr(args, "provider", None) or config.default_provider
    model = getattr(args, "model", None) or config.default_model

    try:
        if provider_name == "ollama":
            from aether.providers.ollama_provider import OllamaProvider
            from aether.providers.types import ProviderConfig
            return OllamaProvider(ProviderConfig(model=model or "llama3"))

        elif provider_name == "anthropic":
            api_key = os.environ.get("ANTHROPIC_API_KEY")
            if not api_key:
                print("Error: ANTHROPIC_API_KEY not set.", file=sys.stderr)
                return None
            from aether.providers.anthropic_provider import AnthropicProvider
            from aether.providers.types import ProviderConfig
            return AnthropicProvider(ProviderConfig(model=model or "claude-3-5-sonnet-20241022"))

        elif provider_name == "gemini":
            api_key = os.environ.get("GEMINI_API_KEY")
            if not api_key:
                print("Error: GEMINI_API_KEY not set.", file=sys.stderr)
                return None
            from aether.providers.gemini_provider import GeminiProvider
            from aether.providers.types import ProviderConfig
            return GeminiProvider(ProviderConfig(model=model or "gemini-1.5-pro"))

        else:  # openai (default)
            api_key = os.environ.get("OPENAI_API_KEY")
            if not api_key:
                print("Error: OPENAI_API_KEY not set.", file=sys.stderr)
                return None
            from aether.providers.openai_provider import OpenAIProvider
            from aether.providers.types import ProviderConfig
            return OpenAIProvider(ProviderConfig(model=model or "gpt-4o"))

    except ImportError as exc:
        print(f"Error: Provider '{provider_name}' not available: {exc}", file=sys.stderr)
        return None


# ---------------------------------------------------------------------------
# Knowledge subcommands
# ---------------------------------------------------------------------------

def _cmd_knowledge_add(args) -> None:
    path = Path(args.path)
    if not path.exists():
        print(f"Error: Path not found: {path}", file=sys.stderr)
        sys.exit(1)

    team_yaml = _find_team_yaml()
    kb_path = _default_knowledge_db(team_yaml.parent if team_yaml else Path.cwd())

    from aether.knowledge.store import KnowledgeStore
    from aether.knowledge.ingestion import DocumentIngester

    # Ensure .aether/ directory exists
    Path(kb_path).parent.mkdir(parents=True, exist_ok=True)

    store = KnowledgeStore(kb_path)
    ingester = DocumentIngester(store)

    count = ingester.ingest(path)
    after = store.count()

    print(f"✓ Indicizzati {count} chunk{'i' if count != 1 else ''} da {path}")
    print(f"  Totale knowledge base: {after} chunk{'i' if after != 1 else ''}")


def _cmd_knowledge_list(args) -> None:
    team_yaml = _find_team_yaml()
    kb_path = _default_knowledge_db(team_yaml.parent if team_yaml else Path.cwd())

    if not Path(kb_path).exists():
        print("Knowledge base vuota (nessun documento indicizzato).")
        return

    from aether.knowledge.store import KnowledgeStore
    store = KnowledgeStore(kb_path)
    sources = store.list_sources()

    if not sources:
        print("Knowledge base vuota.")
        return

    total = store.count()
    print(f"Knowledge base: {total} chunk{'i' if total != 1 else ''} da {len(sources)} sorgenti\n")
    for source in sources:
        chunks = store.get_by_source(source)
        print(f"  {source} ({len(chunks)} chunk{'i' if len(chunks) != 1 else ''})")


def _cmd_knowledge_clear(args) -> None:
    team_yaml = _find_team_yaml()
    kb_path = _default_knowledge_db(team_yaml.parent if team_yaml else Path.cwd())

    if not Path(kb_path).exists():
        print("Knowledge base già vuota.")
        return

    from aether.knowledge.store import KnowledgeStore
    store = KnowledgeStore(kb_path)
    count = store.count()
    store.clear()
    print(f"✓ Knowledge base svuotata ({count} chunk{'i' if count != 1 else ''} rimossi).")


def _cmd_knowledge_search(args) -> None:
    team_yaml = _find_team_yaml()
    kb_path = _default_knowledge_db(team_yaml.parent if team_yaml else Path.cwd())

    if not Path(kb_path).exists():
        print("Knowledge base vuota.")
        return

    from aether.knowledge.store import KnowledgeStore
    store = KnowledgeStore(kb_path)
    query = " ".join(args.query) if isinstance(args.query, list) else args.query
    results = store.search(query, limit=args.limit or 5)

    if not results:
        print(f"Nessun risultato per: {query!r}")
        return

    print(f"Risultati per {query!r} ({len(results)} chunk{'i' if len(results) != 1 else ''}):\n")
    for i, chunk in enumerate(results, 1):
        print(f"  [{i}] {chunk.source} (chunk {chunk.chunk_index})")
        preview = chunk.content[:200].replace("\n", " ")
        print(f"      {preview}...")
        print()


# ---------------------------------------------------------------------------
# Team status
# ---------------------------------------------------------------------------

def _cmd_team_status(args) -> None:
    team_yaml = _find_team_yaml()
    if team_yaml is None:
        print("Error: No team.yaml found.", file=sys.stderr)
        sys.exit(1)

    try:
        config = _load_team_config(team_yaml)
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)

    print(f"Team: {config.name}")
    print(f"Provider: {config.default_provider}" + (f" / {config.default_model}" if config.default_model else ""))
    if config.knowledge_path:
        print(f"Knowledge: {config.knowledge_path}")
    print()
    print(f"Agenti ({len(config.agents)}):")
    for agent in config.agents:
        delegations = agent.delegates_to()
        rel_str = f" → {', '.join(delegations)}" if delegations else ""
        print(f"  [{agent.name}] role={agent.role}{rel_str}")


# ---------------------------------------------------------------------------
# Agent subcommands
# ---------------------------------------------------------------------------

def _cmd_agent_memory(args) -> None:
    print(f"[Agent memory] Agente: {args.agent_name}")
    print("  (La memoria persistente cross-session sarà disponibile in P1.)")
    print("  Tip: usa 'aether knowledge list' per vedere la knowledge base del team.")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="aether",
        description="Aether — runtime for persistent AI agent teams",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # ---- init ----
    init_p = subparsers.add_parser("init", help="Scaffold a new team project")
    init_p.add_argument("name", nargs="?", help="Project directory name (default: current dir)")
    init_p.add_argument("--provider", choices=["openai", "anthropic", "ollama", "gemini"],
                        default="openai", help="Default AI provider")
    init_p.add_argument("--model", help="Default model name")

    # ---- run ----
    run_p = subparsers.add_parser("run", help="Run a task through the team")
    run_p.add_argument("task", nargs="+", help="Task description")
    run_p.add_argument("--provider", choices=["openai", "anthropic", "ollama", "gemini"],
                       help="Override provider")
    run_p.add_argument("--model", help="Override model")

    # ---- knowledge ----
    know_p = subparsers.add_parser("knowledge", help="Manage team knowledge base")
    know_sub = know_p.add_subparsers(dest="knowledge_command", required=True)

    know_add = know_sub.add_parser("add", help="Ingest documents")
    know_add.add_argument("path", help="File or directory to ingest")

    know_sub.add_parser("list", help="List indexed sources")
    know_sub.add_parser("clear", help="Remove all knowledge chunks")

    know_search = know_sub.add_parser("search", help="Search knowledge base")
    know_search.add_argument("query", nargs="+", help="Search query")
    know_search.add_argument("--limit", type=int, default=5, help="Max results")

    # ---- team ----
    team_p = subparsers.add_parser("team", help="Team management")
    team_sub = team_p.add_subparsers(dest="team_command", required=True)
    team_sub.add_parser("status", help="Show team status")

    # ---- agent ----
    agent_p = subparsers.add_parser("agent", help="Agent management")
    agent_sub = agent_p.add_subparsers(dest="agent_command", required=True)
    mem_p = agent_sub.add_parser("memory", help="Show agent memory")
    mem_p.add_argument("agent_name", help="Agent name")

    args = parser.parse_args()

    dispatch = {
        "init": _cmd_init,
        "run": _cmd_run,
        "knowledge": {
            "add": _cmd_knowledge_add,
            "list": _cmd_knowledge_list,
            "clear": _cmd_knowledge_clear,
            "search": _cmd_knowledge_search,
        },
        "team": {
            "status": _cmd_team_status,
        },
        "agent": {
            "memory": _cmd_agent_memory,
        },
    }

    handler = dispatch.get(args.command)
    if callable(handler):
        handler(args)
    elif isinstance(handler, dict):
        sub_key = getattr(args, f"{args.command}_command", None)
        sub_handler = handler.get(sub_key) if sub_key else None
        if callable(sub_handler):
            sub_handler(args)
        else:
            parser.print_help()
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
